export const MOCK_PROPERTIES = [
  {
    _id: "1",
    title: "Boudha Residence",
    type: "House",
    location: { city: "Kathmandu", country: "Nepal", address: "Boudha Stupa Road" },
    price: 320000,
    bedrooms: 4,
    bathrooms: 3,
    area: 2800,
    isAvailable: true,
    description: "A magnificent traditional residence steps from the iconic Boudhanath Stupa. This home blends Newari architectural heritage with modern comforts—exposed brick, carved wooden windows, and a rooftop terrace with panoramic views of the Himalayan foothills. Features a lush inner courtyard garden, sunlit study, and gourmet kitchen.",
    imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
  },
  {
    _id: "2",
    title: "Pokhara Lakeside Villa",
    type: "Villa",
    location: { city: "Pokhara", country: "Nepal", address: "Lakeside Promenade" },
    price: 485000,
    bedrooms: 5,
    bathrooms: 4,
    area: 4200,
    isAvailable: true,
    description: "Perched on the serene shores of Phewa Lake, this exceptional villa offers uninterrupted views of Machhapuchhre and the Annapurna range. Expansive terraces, infinity-edge pool, and floor-to-ceiling glass bring the mountains inside. A masterpiece of contemporary design fused with local stone and timber.",
    imageUrl: "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&q=80",
  },
  {
    _id: "3",
    title: "Lazimpat Apartment",
    type: "Apartment",
    location: { city: "Kathmandu", country: "Nepal", address: "Lazimpat Street" },
    price: 145000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1100,
    isAvailable: true,
    description: "Sophisticated city-centre apartment in the diplomatic quarter of Lazimpat. High ceilings, polished concrete floors, and warm-toned woodwork define this refined urban retreat. Walkable to galleries, embassies, and the best restaurants in Kathmandu. Concierge building with rooftop garden access.",
    imageUrl: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
  },
  {
    _id: "4",
    title: "Nagarkot Hill Estate",
    type: "Estate",
    location: { city: "Nagarkot", country: "Nepal", address: "Hill View Road" },
    price: 680000,
    bedrooms: 6,
    bathrooms: 5,
    area: 6100,
    isAvailable: true,
    description: "A rare hilltop estate commanding 360° views of eight Himalayan peaks including Everest. This extraordinary property spans three acres of landscaped gardens with a private orchard, guest cottage, yoga pavilion, and heated indoor pool. Crafted from local stone with hand-painted traditional motifs throughout.",
    imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
  },
  {
    _id: "5",
    title: "Thamel Heritage Loft",
    type: "Loft",
    location: { city: "Kathmandu", country: "Nepal", address: "Thamel North" },
    price: 210000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    isAvailable: true,
    description: "An architect-converted heritage loft in the vibrant heart of Thamel. Original exposed brick walls and ornate carved wooden beams contrast beautifully with sleek modern fixtures. Wraparound balcony overlooking the bustling courtyard below. A cultural landmark reinvented as an extraordinary home.",
    imageUrl: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
  },
  {
    _id: "6",
    title: "Chitwan Forest Retreat",
    type: "Retreat",
    location: { city: "Chitwan", country: "Nepal", address: "National Park Border" },
    price: 390000,
    bedrooms: 4,
    bathrooms: 3,
    area: 3400,
    isAvailable: false,
    description: "A breathtaking eco-retreat on the edge of Chitwan National Park. Wake to the calls of exotic birds and elephants passing through the tree line. Built entirely from sustainably harvested timber and bamboo, this home integrates with the jungle while providing every modern luxury. Solar-powered, spring-fed, unforgettable.",
    imageUrl: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800&q=80",
  },
];